title: Sabrage Software
email: harry@harrylascelles.com
description: >- # this means to ignore newlines until "baseurl:"
  The Home of Sabrage Software
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.sabragesoftware.com"
markdown: kramdown

google_analytics: UA-27574653-1

plugins:
- jekyll-sitemap
- jekyll-seo-tag
